#!/usr/bin/env python

import sys
import subprocess
from pathlib import Path
from typing import Optional


class WslWrapper:
    def __init__(self, distribution: str):
        self.distribution = distribution

    def cmd(self, command: str, cwd: Optional[Path] = None) -> int:
        return subprocess.run(
            f"wsl -d {command}",
            cwd=cwd,
            shell=True,
        ).returncode


def main():
    wsl = WslWrapper("Ubuntu")
    p = Path(sys.argv[1])

    # send sigint go2rtc
    go2rtc_stopped = wsl.cmd(
        "pkill -SIGSTOP go2rtc",
    )

    # stop gphoto2
    wsl.cmd(
        "pkill -SIGINT gphoto2",
    )

    # wait until process is gone
    wsl.cmd(
        (
            "i=5;"
            "while pgrep gphoto2; do "
            "sleep 0.2;"
            "i=((i-1));"
            "[[ $i -le 0 ]] && pkill -SIGKILL gphoto2;"
            "done"
        )
    )

    gphoto2_result = wsl.cmd(
        f"gphoto2 --capture-image-and-download --filename {p.name}",
        cwd=p.parent,
    )

    if go2rtc_stopped == 0:
        # continue if stopped
        wsl.cmd(
            "pkill -SIGCONT go2rtc",
            cwd=p.parent,
        )
    else:
        # start go2rtc if not running
        wsl.cmd("nohup go2rtc -config /etc/go2rtc &")

    return gphoto2_result


if __name__ == "__main__":
    sys.exit(main())
